#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_API_CREATED == "true"

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "nightly: x86-64-unknown-linux-gnu"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  nightly_script:
    - bash .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash ${CLOUDSMITH_API_KEY}


task:
  only_if: $CIRRUS_API_CREATED == "true"

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "nightly: x86-64-unknown-linux-musl"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  nightly_script:
    - bash .ci-scripts/x86-64-unknown-linux-musl-nightly.bash ${CLOUDSMITH_API_KEY}

task:
  only_if: $CIRRUS_API_CREATED == "true"

  osx_instance:
    image: mojave-xcode-11.2.1

  name: "nightly: x86-64-apple-darwin"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  install_script:
    - brew install coreutils python
    - pip3 install --upgrade cloudsmith-cli

  nightly_script:
    - export TZ=utc
    - bash .ci-scripts/x86-64-apple-darwin-nightly.bash ${CLOUDSMITH_API_KEY}

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "release: x86-64-unknown-linux-gnu"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  release_script:
    - bash .ci-scripts/x86-64-unknown-linux-gnu-release.bash ${CLOUDSMITH_API_KEY}

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "release: x86-64-unknown-linux-musl"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  release_script:
    - bash .ci-scripts/x86-64-unknown-linux-musl-release.bash ${CLOUDSMITH_API_KEY}

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  osx_instance:
    image: mojave-xcode-11.2.1

  name: "release: x86-64-apple-darwin"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  install_script:
    - brew install coreutils python
    - pip3 install --upgrade cloudsmith-cli

  release_script:
    - bash .ci-scripts/x86-64-apple-darwin-release.bash ${CLOUDSMITH_API_KEY}

#
# Pull Request Tasks
#

task:
  only_if: $CIRRUS_PR != ''

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191106
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-linux-gnu"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` glibc"
    populate_script: make libs build_flags=-j8 verbose=1

  configure_script:
    - make configure verbose=1
  build_script:
    - make build build_flags=-j8 verbose=1
  test_script:
    - make test-ci verbose=1

task:
  only_if: $CIRRUS_PR != ''

  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191106
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-linux-musl"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` musl"
    populate_script: make libs build_flags=-j8 verbose=1

  configure_script:
    - make configure verbose=1
  build_script:
    - make build build_flags=-j8 verbose=1
  test_script:
    - make test-ci verbose=1

task:
  only_if: $CIRRUS_PR != ''

  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 8
    memory: 24

  name: "PR: x86-64-unknown-freebsd12.0"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y cmake gmake libunwind git

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` freebsd12"
    populate_script: gmake libs build_flags=-j8 verbose=1

  configure_script:
    - gmake configure verbose=1
  build_script:
    - gmake build build_flags=-j8 verbose=1
  test_script:
    - gmake test-ci verbose=1

task:
  only_if: $CIRRUS_PR != ''

  osx_instance:
    image: mojave-xcode-11.2.1

  name: "PR: x86-64-apple-darwin"

  install_script:
    - brew install coreutils

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` macos"
    populate_script: make libs build_flags=-j8 verbose=1

  configure_script:
    - make configure verbose=1
  build_script:
    - make build build_flags=-j8 verbose=1
  test_script:
    - make test-ci verbose=1

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

task:
  only_if: $CIRRUS_PR != ''

  windows_container:
    dockerfile: .ci-dockerfiles/windowsservercore/Dockerfile
    os_version: 2019
    cpu: 8
    memory: 24

  name: "PR: x86-64-pc-windows-msvc"

  libs_cache:
    folder: build/libs
    fingerprint_script: powershell.exe -NoLogo -Command "(Get-FileHash -Path lib\CMakeLists.txt).Hash"
    populate_script:
      - powershell.exe -NoLogo -File .\make.ps1 libs -Generator "Visual Studio 16 2019"

  config_script:
    - powershell.exe -NoLogo -File .\make.ps1 configure -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"
  build_script:
    - powershell.exe -NoLogo -File .\make.ps1 build -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"
  test_script:
    - powershell.exe -NoLogo -File .\make.ps1 test -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"

    # install_script: powershell.exe -NoLogo -File .\make.ps1 install -Config Release -InstallPath "build\install\release"
  # package_script: powershell.exe -NoLogo -File .\make.ps1 package -Config Release -InstallPath "build\install\release" -Version date
  # upload_script: powershell.exe -NoLogo -Command "$version = (Get-Date).ToString(""""yyyyMMdd""""); & cloudsmith push raw --version $version --api-key 1cc732891a064c6542e3632a6ee281b69dbdce18 --summary """"Pony compiler"""" --description """"https://github.com/ponylang/ponyc"""" main-pony/pony-nightlies build\ponyc-x86_64-pc-windows-msvc-$version.zip

  binary_artifacts:
    path: build/*.zip
