version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  # Jobs for building and testing with ponyc system installed cross-llvm
  cross-arm:
    docker:
      - image: ponylang/ponyc-ci-cross-arm:20200127
        user: pony
    steps:
      - checkout
      # restore or build libs
      - restore_cache:
          keys:
            - libs-cache-cross-arm-{{ checksum "lib/CMakeLists.txt" }}
      - run: if [ ! -d build/libs ]; then make libs llvm_archs="X86;ARM"; fi
      - save_cache:
          key: libs-cache-cross-arm-{{ checksum "lib/CMakeLists.txt" }}
          paths:
            - build/libs
      # build and test for x86_64 first
      - run: make configure config=release verbose=1
      - run: make build config=release verbose=1 build_flags=-j3
      - run: make test-ci config=release verbose=1
      # build libponyrt for ARM
      - run: make cross-libponyrt config=release verbose=1 CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ arch=armv7-a tune=cortex-a9 cross_triple=arm-unknown-linux-gnueabi
      # run stdlib tests on ARM
      - run: make test-cross-ci config=release verbose=1 PONYPATH=../armv7-a/release cross_arch=armv7-a cross_cpu=cortex-a9 cross_triple=arm-unknown-linux-gnueabi cross_linker=arm-linux-gnueabi-gcc cross_runner="qemu-arm-static -cpu cortex-a9 -L /usr/local/arm-linux-gnueabi/libc"
      - zulip/status:
          fail_only: true

  cross-aarch64:
    docker:
      - image: ponylang/ponyc-ci-cross-aarch64:20200212
        user: pony
    steps:
      - checkout
      # restore or build libs
      - restore_cache:
          keys:
            - libs-cache-cross-aarch64-{{ checksum "lib/CMakeLists.txt" }}
      - run: if [ ! -d build/libs ]; then make libs llvm_archs="X86;ARM"; fi
      - save_cache:
          key: libs-cache-cross-aarch64-{{ checksum "lib/CMakeLists.txt" }}
          paths:
            - build/libs
      # build and test for x86_64 first
      - run: make configure config=release verbose=1
      - run: make build config=release verbose=1 build_flags=-j3
      - run: make test-ci config=release verbose=1
      # build libponyrt for ARM
      - run: make cross-libponyrt config=release verbose=1 CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ arch=armv8-a tune=cortex-a53 cross_triple=aarch64-unknown-linux-gnu
      # run stdlib tests on ARM
      - run: make test-cross-ci config=release verbose=1 PONYPATH=../armv8-a/release cross_arch=armv8-a cross_cpu=cortex-a53 cross_triple=aarch64-unknown-linux-gnu cross_linker=aarch64-linux-gnu-gcc cross_runner="qemu-aarch64-static -cpu cortex-a53 -L /usr/local/aarch64-linux-gnu/libc"
      - zulip/status:
          fail_only: true


workflows:
  version: 2.1

  # PR acceptance tests, shouldn't run on `master` or `release` branches
  pr-acceptance-tests:
    jobs:
      # p2 cross compilation tests
      - cross-arm:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - release
      - cross-aarch64:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - release

      # - cross-llvm-701-armhf:
      #     context: org-global
      #     filters:
      #       branches:
      #         ignore:
      #           - master
      #           - release

#     Currently don't pass
#      - cross-llvm-701-release-aarch64:
#           requires:
#             - lib-llvm-ubuntu-release
#           context: org-global
#          filters:
#            branches:
#              ignore:
#                - master
#                - release
#
#      - cross-llvm-701-debug-aarch64:
#           requires:
#             - lib-llvm-ubuntu-debugS
#           context: org-global
#          filters:
#            branches:
#              ignore:
#                - master
#                - release
